### ISSUE TITLE
The result not same on iOS

### ISSUE THREAD

**Issue by tanyuantj** [VladKarpushin/out_of_focus_deblur#1]
I ran the code on an iOS simulator and the result is quite different with what expected. Here is my result:
![result](https://user-images.githubusercontent.com/29684652/59549858-55de2900-8f96-11e9-9b35-1fcf69a98b61.jpg)
Not sure what the problem is.

**Comment by VladKarpushin** [comment]
Because original size image should be used. I can send a link to the image

**Comment by VladKarpushin** [comment]
https://user-images.githubusercontent.com/40189112/51956454-455f6300-247a-11e9-9ac6-a9c90333b1c6.JPG

**Comment by TomLuna** [comment]
That's the problem, Thanks @VladKarpushin!
The output now is perfectly same with [https://github.com/VladKarpushin/out_of_focus_deblur/blob/master/www/images/recovered.jpg](url)
I'll close this issue.

**Comment by busuidemeng** [comment]
> 
> 
> That's the problem, Thanks @VladKarpushin!
> The output now is perfectly same with [https://github.com/VladKarpushin/out_of_focus_deblur/blob/master/www/images/recovered.jpg](url)
> I'll close this issue.

我用了原图 最好效果还是您之前的那个？ 我需要做什么吗
